
#line 3 "lex._fmsp_assembler_yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer _fmsp_assembler_yy_create_buffer
#define yy_delete_buffer _fmsp_assembler_yy_delete_buffer
#define yy_flex_debug _fmsp_assembler_yy_flex_debug
#define yy_init_buffer _fmsp_assembler_yy_init_buffer
#define yy_flush_buffer _fmsp_assembler_yy_flush_buffer
#define yy_load_buffer_state _fmsp_assembler_yy_load_buffer_state
#define yy_switch_to_buffer _fmsp_assembler_yy_switch_to_buffer
#define yyin _fmsp_assembler_yyin
#define yyleng _fmsp_assembler_yyleng
#define yylex _fmsp_assembler_yylex
#define yylineno _fmsp_assembler_yylineno
#define yyout _fmsp_assembler_yyout
#define yyrestart _fmsp_assembler_yyrestart
#define yytext _fmsp_assembler_yytext
#define yywrap _fmsp_assembler_yywrap
#define yyalloc _fmsp_assembler_yyalloc
#define yyrealloc _fmsp_assembler_yyrealloc
#define yyfree _fmsp_assembler_yyfree

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE _fmsp_assembler_yyrestart(_fmsp_assembler_yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int _fmsp_assembler_yyleng;

extern FILE *_fmsp_assembler_yyin, *_fmsp_assembler_yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up _fmsp_assembler_yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up _fmsp_assembler_yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via _fmsp_assembler_yyrestart()), so that the user can continue scanning by
	 * just pointing _fmsp_assembler_yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when _fmsp_assembler_yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int _fmsp_assembler_yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow _fmsp_assembler_yywrap()'s to do buffer switches
 * instead of setting up a fresh _fmsp_assembler_yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void _fmsp_assembler_yyrestart (FILE *input_file  );
void _fmsp_assembler_yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE _fmsp_assembler_yy_create_buffer (FILE *file,int size  );
void _fmsp_assembler_yy_delete_buffer (YY_BUFFER_STATE b  );
void _fmsp_assembler_yy_flush_buffer (YY_BUFFER_STATE b  );
void _fmsp_assembler_yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void _fmsp_assembler_yypop_buffer_state (void );

static void _fmsp_assembler_yyensure_buffer_stack (void );
static void _fmsp_assembler_yy_load_buffer_state (void );
static void _fmsp_assembler_yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER _fmsp_assembler_yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE _fmsp_assembler_yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE _fmsp_assembler_yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE _fmsp_assembler_yy_scan_bytes (yyconst char *bytes,int len  );

void *_fmsp_assembler_yyalloc (yy_size_t  );
void *_fmsp_assembler_yyrealloc (void *,yy_size_t  );
void _fmsp_assembler_yyfree (void *  );

#define yy_new_buffer _fmsp_assembler_yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        _fmsp_assembler_yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            _fmsp_assembler_yy_create_buffer(_fmsp_assembler_yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        _fmsp_assembler_yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            _fmsp_assembler_yy_create_buffer(_fmsp_assembler_yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define _fmsp_assembler_yywrap(n) 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *_fmsp_assembler_yyin = (FILE *) 0, *_fmsp_assembler_yyout = (FILE *) 0;

typedef int yy_state_type;

extern int _fmsp_assembler_yylineno;

int _fmsp_assembler_yylineno = 1;

extern char *_fmsp_assembler_yytext;
#define yytext_ptr _fmsp_assembler_yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up _fmsp_assembler_yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	_fmsp_assembler_yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 71
#define YY_END_OF_BUFFER 72
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[246] =
    {   0,
        0,    0,   72,   70,    2,    2,   70,   70,   26,   66,
       67,   35,   68,   36,   70,   17,   17,   28,   32,   12,
       31,   27,   69,   69,   69,   69,   69,   69,   69,   69,
       69,   69,   69,   69,   69,   69,   69,   69,   69,   21,
       69,   25,   70,    2,    4,    2,   30,    0,    1,    9,
       22,   17,    0,   13,   34,   29,   33,   14,   69,   69,
       69,   69,   69,   69,   40,   69,   23,   69,   69,   69,
       69,   69,    7,   69,   69,   69,   69,   69,   69,   41,
       69,   69,   69,   10,    0,    3,   16,   11,    6,   43,
       42,   69,   69,   20,   24,   69,   38,   37,   39,   69,

       69,   19,   69,   18,   69,   69,   69,   55,   56,   69,
        8,   69,   16,   69,   69,   69,   69,   69,   69,   69,
       69,   69,   69,    0,    0,   69,   69,   16,   69,   69,
       69,   69,   69,   69,   69,   69,   69,   69,   69,    0,
        0,   69,   69,   69,   69,   69,   69,   69,   15,   69,
       69,   69,   69,   69,   69,   69,   69,   69,   69,   69,
       69,    0,   69,   69,   69,   69,   69,   69,   69,   69,
       16,   69,   44,   69,   69,   69,   69,   69,   69,   69,
       69,   48,   49,    0,   69,   69,   69,   69,   69,   57,
       59,   61,   69,   45,   46,   69,   69,   69,   69,   69,

       69,    0,   69,   62,   63,   64,   65,   54,   69,   69,
       69,   69,   69,   69,    0,   69,   69,   69,   47,   50,
       58,   51,    0,   60,   69,   69,    0,   52,   53,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    5,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    6,    1,    7,    1,    1,    8,    1,    9,
       10,    1,   11,   12,   13,   14,    1,   15,   16,   17,
       18,   19,   20,   21,   22,   23,   20,   24,    1,   25,
       26,   27,   28,    1,   29,   30,   31,   32,   33,   34,
       35,   36,   37,   38,   35,   39,   40,   41,   42,   43,
       35,   44,   45,   46,   47,   48,   49,   50,   51,   35,
       52,    1,   53,    1,   54,    1,   55,   55,   55,   56,

       57,   58,   35,   59,   60,   35,   35,   35,   35,   61,
       35,   35,   35,   35,   62,   63,   64,   35,   35,   65,
       35,   35,    1,   66,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[67] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    1,    1,    1,    1,    1,    3,    3,
        3,    3,    3,    3,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    1,    1,    4,    3,    3,    3,    3,    4,    4,
        4,    4,    4,    4,    5,    1
    } ;

static yyconst flex_int16_t yy_base[254] =
    {   0,
        0,   65,  321,  322,  322,  317,  293,  315,  322,  322,
      322,  291,  322,  322,  302,  250,   57,  322,   56,  288,
       57,  322,  272,    0,  273,   44,  262,   39,   52,  270,
      278,   46,   47,  279,   65,  276,  274,   55,  263,  322,
      244,  277,   98,  322,  276,  322,  322,  298,  322,  322,
      322,   89,    0,  274,  322,  322,  322,  322,    0,  267,
       73,  266,  261,  244,    0,  250,    0,  246,  250,  244,
      248,  244,    0,  253,   62,  236,  241,  243,  242,    0,
      103,  240,  222,  322,  118,  322,    0,  322,    0,    0,
        0,  228,  227,  322,    0,  103,    0,    0,    0,  226,

      225,  322,  218,  322,  230,  222,  221,  110,    0,  212,
        0,  210,    0,  229,  235,  216,  215,   92,  229,  206,
      222,  229,  228,  121,   97,  204,  112,    0,  233,  211,
      224,  223,  212,  214,  119,  200,  214,  204,  203,  122,
      211,  191,  229,  232,  225,  113,  193,  192,    0,  201,
      199,  193,  192,  205,  186,  185,  184,  180,  182,  190,
      189,  200,  174,  177,  176,  175,  174,  164,  163,  162,
        0,  179,    0,  178,  177,  167,  177,  183,  182,  137,
      165,    0,    0,  147,  128,  127,  126,  125,  122,    0,
        0,    0,  151,    0,    0,  137,  138,  131,  130,  125,

      128,  146,  122,    0,    0,    0,    0,    0,  124,  132,
      128,  127,  108,  125,  127,  105,  123,  119,    0,    0,
        0,    0,  123,    0,  129,  119,  117,    0,    0,  135,
      136,  137,  138,  115,  143,  141,  143,  144,  145,  110,
      136,   82,  146,  322,  322,  194,  198,  202,  206,  208,
      210,  212,  214
    } ;

static yyconst flex_int16_t yy_def[254] =
    {   0,
      245,    1,  245,  245,  245,  245,  245,  246,  245,  245,
      245,  245,  245,  245,  245,  247,  245,  245,  245,  245,
      245,  245,  248,  248,  248,  248,  248,  248,  248,  248,
      248,  248,  248,  248,  248,  248,  248,  248,  248,  245,
      248,  245,  245,  245,  245,  245,  245,  246,  245,  245,
      245,  245,  249,  245,  245,  245,  245,  245,  248,  248,
      248,  248,  248,  248,  248,  248,  248,  248,  248,  248,
      248,  248,  248,  248,  248,  248,  248,  248,  248,  248,
      248,  248,  248,  245,  245,  245,  250,  245,  248,  248,
      248,  248,  248,  245,  248,  248,  248,  248,  248,  248,

      248,  245,  248,  245,  248,  248,  248,  248,  248,  248,
      248,  248,  251,  248,  248,  248,  248,  248,  248,  248,
      248,  248,  248,  245,  245,  248,  248,  252,  248,  248,
      248,  248,  248,  248,  248,  248,  248,  248,  248,  245,
      245,  248,  248,  248,  248,  248,  248,  248,  253,  248,
      248,  248,  248,  248,  248,  248,  248,  248,  248,  248,
      248,  245,  248,  248,  248,  248,  248,  248,  248,  248,
      253,  248,  248,  248,  248,  248,  248,  248,  248,  248,
      248,  248,  248,  245,  248,  248,  248,  248,  248,  248,
      248,  248,  248,  248,  248,  248,  248,  248,  248,  248,

      248,  245,  248,  248,  248,  248,  248,  248,  248,  248,
      248,  248,  248,  248,  245,  248,  248,  248,  248,  248,
      248,  248,  245,  248,  248,  248,  245,  248,  248,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,    0,  245,  245,  245,  245,  245,
      245,  245,  245
    } ;

static yyconst flex_int16_t yy_nxt[389] =
    {   0,
        4,    4,    5,    6,    4,    7,    8,    9,   10,   11,
       12,   13,   14,   15,   16,   17,   17,   17,   17,   17,
       17,   17,   17,   18,   19,   20,   21,   22,   23,   24,
       25,   24,   26,   27,   24,   28,   29,   30,   31,   24,
       32,   33,   34,   35,   24,   36,   37,   24,   38,   39,
       24,    4,   40,    4,   24,   24,   24,   24,   24,   24,
       24,   24,   24,   41,   24,   42,   43,   44,   65,   43,
       45,   52,   52,   52,   52,   52,   52,   52,   52,   52,
       54,   55,   57,   58,   62,   67,  243,   71,   66,   63,
       73,  244,   74,   76,   68,   72,   80,   77,   81,   85,

       86,  140,   85,   52,   52,   52,   52,   52,   52,   52,
       52,   52,   90,  102,  124,  103,   91,  108,  109,   85,
       86,  116,   85,  117,  133,  124,  140,  143,  134,  144,
      145,  167,  146,  147,  148,  125,  156,  157,  141,  231,
      231,  233,  233,  232,  232,  237,  125,  237,  239,  239,
      243,  242,  238,  241,  238,  244,  110,  236,  235,  230,
      229,  228,  227,  141,  226,  225,  168,  224,  223,  222,
      221,  220,  219,  218,  217,  216,  215,  214,  213,  212,
      211,  210,  209,  208,  207,  234,  234,  206,  205,  204,
      203,  202,  240,  240,   48,   48,   48,   48,   48,   52,

      201,  200,   52,   59,   59,   59,   59,   87,   87,  113,
      113,  128,  128,  149,  149,  171,  171,  199,  198,  197,
      196,  195,  194,  193,  192,  191,  190,  189,  188,  187,
      186,  185,  184,  183,  182,  181,  180,  179,  178,  177,
      176,  175,  174,  173,  172,  170,  169,  166,  165,  164,
      163,  162,  161,  160,  159,  158,  155,  154,  153,  152,
      151,  150,  142,  139,  138,  137,  136,  135,  132,  131,
      130,  129,  127,  126,  123,  122,  121,  120,  119,  118,
      115,  114,  112,  111,  107,  106,  105,  104,  101,  100,
       99,   98,   97,   96,   95,   94,   93,   92,   89,   88,

       49,   47,   84,   83,   82,   79,   78,   75,   70,   69,
       64,   61,   60,   56,   53,   51,   50,   49,   47,   46,
      245,    3,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245
    } ;

static yyconst flex_int16_t yy_chk[389] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    2,    2,   28,    2,
        2,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       19,   19,   21,   21,   26,   29,  242,   32,   28,   26,
       33,  242,   33,   35,   29,   32,   38,   35,   38,   43,

       43,  125,   43,   52,   52,   52,   52,   52,   52,   52,
       52,   52,   61,   75,  108,   75,   61,   81,   81,   85,
       85,   96,   85,   96,  118,  124,  140,  127,  118,  127,
      127,  146,  127,  127,  127,  108,  135,  135,  125,  230,
      231,  232,  233,  230,  231,  236,  124,  237,  238,  239,
      243,  241,  236,  240,  237,  243,   81,  235,  234,  227,
      226,  225,  223,  140,  218,  217,  146,  216,  215,  214,
      213,  212,  211,  210,  209,  203,  202,  201,  200,  199,
      198,  197,  196,  193,  189,  232,  233,  188,  187,  186,
      185,  184,  238,  239,  246,  246,  246,  246,  246,  247,

      181,  180,  247,  248,  248,  248,  248,  249,  249,  250,
      250,  251,  251,  252,  252,  253,  253,  179,  178,  177,
      176,  175,  174,  172,  170,  169,  168,  167,  166,  165,
      164,  163,  162,  161,  160,  159,  158,  157,  156,  155,
      154,  153,  152,  151,  150,  148,  147,  145,  144,  143,
      142,  141,  139,  138,  137,  136,  134,  133,  132,  131,
      130,  129,  126,  123,  122,  121,  120,  119,  117,  116,
      115,  114,  112,  110,  107,  106,  105,  103,  101,  100,
       93,   92,   83,   82,   79,   78,   77,   76,   74,   72,
       71,   70,   69,   68,   66,   64,   63,   62,   60,   54,

       48,   45,   42,   41,   39,   37,   36,   34,   31,   30,
       27,   25,   23,   20,   16,   15,   12,    8,    7,    6,
        3,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int _fmsp_assembler_yy_flex_debug;
int _fmsp_assembler_yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *_fmsp_assembler_yytext;
#line 1 "fm_sp_assembler.lex"
/* =====================================================================
 *
 * The MIT License (MIT)
 * Copyright 2009,2010, Freescale Semiconductor, Inc., All Rights Reserved. 
 * Copyright 2020 NXP
 *
 * Permission is hereby granted, free of charge, to any person obtaining
 * a copy of this software and associated documentation files (the
 * "Software"), to deal in the Software without restriction, including
 * without limitation the rights to use, copy, modify, merge, publish,
 * distribute, sublicense, and/or sell copies of the Software, and to
 * permit persons to whom the Software is furnished to do so, subject to
 * the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included
 * in all copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
 * IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
 * CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
 * TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
 * SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 *
 * Special Notes on Selected Files
 * -------------------------------
 *
 * Some files in the Freescale FMC package are generated from skeleton files
 * associated with the Flex and Bison programs.
 *
 * The Bison skeleton files are distributed under GPLv2 but with the following
 * special exception (which applies to the Freescale FMC package):
 *
 * As a special exception, you may create a larger work that contains
 * part or all of the Bison parser skeleton and distribute that work
 * under terms of your choice, so long as that work isn't itself a
 * parser generator using the skeleton or a modified version thereof
 * as a parser skeleton.  Alternatively, if you modify or redistribute
 * the parser skeleton itself, you may (at your option) remove this
 * special exception, which will cause the skeleton and the resulting
 * Bison output files to be licensed under the GNU General Public
 * License without this special exception.
 *
 * The Flex skeleton file is unrestricted.  It's License statement states,
 * in reference to the license of the flex tool itself (which is 2-clause BSD):
 *
 * Note that the "flex.skl" scanner skeleton carries no copyright notice.
 * You are free to do whatever you please with scanners generated using
 * flex; for them, you are not even bound by the above copyright.
 *
 * Only the generated scanner is contained in the Freescale FMC package.
 *
 * Packet Engine Soft Parser Lexical Analyzer.
 *
 * --------------------------------------------------------------------------*/
#line 15 "fm_sp_assembler.lex"
#include <string.h>
#include <stdlib.h>
#include <errno.h>

#include "fm_sp_private.h"
#include "fm_sp_assembler.tab.h"

#ifdef _MSC_VER
#pragma warning(disable : 4996)
#pragma warning(disable : 4003)
#pragma warning(disable : 4018)
#endif

#define YY_DECL int _fmsp_assembler_yylex(void                             *lval_p, \
                                          _fmsp_assembler_parser_context_t *context_p)

#define _FMSP_MALLOC_FAIL_EXIT_PARSE                                  \
   context_p->assemble_failed = true;                                 \
   context_p->assemble_msg_composition_error = fmsp_malloc_failure_e; \
   yyterminate();

/* Deal with warnings generated by flex code */

#if defined(PLATFORM_ppc_750)
#define size_t int
#endif

int   _fmsp_assembler_yyget_lineno  (void);
FILE *_fmsp_assembler_yyget_in      (void);
FILE *_fmsp_assembler_yyget_out     (void);
int   _fmsp_assembler_yyget_leng    (void);
char *_fmsp_assembler_yyget_text    (void);
void  _fmsp_assembler_yyset_lineno  (int   line_number );
void  _fmsp_assembler_yyset_in      (FILE *in_str );
void  _fmsp_assembler_yyset_out     (FILE *out_str );
int   _fmsp_assembler_yyget_debug   (void);
void  _fmsp_assembler_yyset_debug   (int   bdebug );
int   _fmsp_assembler_yylex_destroy (void);

#line 691 "lex._fmsp_assembler_yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int _fmsp_assembler_yylex_destroy (void );

int _fmsp_assembler_yyget_debug (void );

void _fmsp_assembler_yyset_debug (int debug_flag  );

YY_EXTRA_TYPE _fmsp_assembler_yyget_extra (void );

void _fmsp_assembler_yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *_fmsp_assembler_yyget_in (void );

void _fmsp_assembler_yyset_in  (FILE * in_str  );

FILE *_fmsp_assembler_yyget_out (void );

void _fmsp_assembler_yyset_out  (FILE * out_str  );

int _fmsp_assembler_yyget_leng (void );

char *_fmsp_assembler_yyget_text (void );

int _fmsp_assembler_yyget_lineno (void );

void _fmsp_assembler_yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int _fmsp_assembler_yywrap (void );
#else
extern int _fmsp_assembler_yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO fwrite( _fmsp_assembler_yytext, _fmsp_assembler_yyleng, 1, _fmsp_assembler_yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( _fmsp_assembler_yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( _fmsp_assembler_yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, _fmsp_assembler_yyin))==0 && ferror(_fmsp_assembler_yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(_fmsp_assembler_yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int _fmsp_assembler_yylex (void);

#define YY_DECL int _fmsp_assembler_yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after _fmsp_assembler_yytext and _fmsp_assembler_yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( _fmsp_assembler_yyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(_fmsp_assembler_yytext[_fmsp_assembler_yyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 63 "fm_sp_assembler.lex"

#line 878 "lex._fmsp_assembler_yy.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! _fmsp_assembler_yyin )
			_fmsp_assembler_yyin = stdin;

		if ( ! _fmsp_assembler_yyout )
			_fmsp_assembler_yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			_fmsp_assembler_yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				_fmsp_assembler_yy_create_buffer(_fmsp_assembler_yyin,YY_BUF_SIZE );
		}

		_fmsp_assembler_yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of _fmsp_assembler_yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 246 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 322 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
*yy_cp = (yy_hold_char); /* undo effects of setting up _fmsp_assembler_yytext */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up _fmsp_assembler_yytext again */
YY_RULE_SETUP
#line 64 "fm_sp_assembler.lex"
/* Ignore comments */
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 66 "fm_sp_assembler.lex"
{
                  context_p->line_number++;
                  //return END_OF_LINE;
               }
	YY_BREAK
case 3:
*yy_cp = (yy_hold_char); /* undo effects of setting up _fmsp_assembler_yytext */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up _fmsp_assembler_yytext again */
YY_RULE_SETUP
#line 71 "fm_sp_assembler.lex"
{
                  //return BLANK_LINE;
               }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 75 "fm_sp_assembler.lex"
{
                  return START_RAW_INSTRUCTION;
               }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 79 "fm_sp_assembler.lex"
{
                  return ONESCOMP;
               }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 83 "fm_sp_assembler.lex"
{
                  return AND;
               }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 87 "fm_sp_assembler.lex"
{
                  return OR;
               }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 91 "fm_sp_assembler.lex"
{
                  return XOR;
               }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 95 "fm_sp_assembler.lex"
{
                  return INCREMENT;
               }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 99 "fm_sp_assembler.lex"
{
                  return SET_BITS;
               }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 103 "fm_sp_assembler.lex"
{
                  return CONCAT;
               }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 107 "fm_sp_assembler.lex"
{
                  return ASSIGN;
               }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 111 "fm_sp_assembler.lex"
{
                  return SHIFT_LEFT;
               }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 115 "fm_sp_assembler.lex"
{
                  return SHIFT_RIGHT;
               }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 119 "fm_sp_assembler.lex"
{
                  ((YYSTYPE *)lval_p)->string = strdup(_fmsp_assembler_yytext);
                  return HEX_WORD;
               }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 124 "fm_sp_assembler.lex"
{
                  ((YYSTYPE *)lval_p)->string = strdup(_fmsp_assembler_yytext);
                  return HEX_VALUE;
               }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 129 "fm_sp_assembler.lex"
{
                  char *tmp_str_p = strdup(_fmsp_assembler_yytext);
                  errno = 0;
                  ((YYSTYPE *)lval_p)->integer = (int) strtol(_fmsp_assembler_yytext,
                                                              (char **)NULL,
                                                              10);
                  if (errno != 0)
                  {
                     context_p->assemble_failed = true;
                     yyterminate();
                  }

                  free (tmp_str_p);

                  return DEC_VALUE;
               }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 146 "fm_sp_assembler.lex"
{
                  return START_RESULT_ARRAY;
               }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 150 "fm_sp_assembler.lex"
{
                  return START_PARAMETER_ARRAY;
               }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 154 "fm_sp_assembler.lex"
{
                  return START_FRAME_WINDOW;
               }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 158 "fm_sp_assembler.lex"
{
                  return RIGHT_BRACKET;
               }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 162 "fm_sp_assembler.lex"
{
                  return BRIDGE;
               }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 166 "fm_sp_assembler.lex"
{
                  return IF;
               }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 170 "fm_sp_assembler.lex"
{
                  return HXS;
               }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 174 "fm_sp_assembler.lex"
{
                  return PIPE;
               }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 178 "fm_sp_assembler.lex"
{
                  return AMPERSAND;
               }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 182 "fm_sp_assembler.lex"
{
                  return QUESTION;
               }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 186 "fm_sp_assembler.lex"
{
                  return COLON;
               }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 190 "fm_sp_assembler.lex"
{
                  return EQUAL;
               }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 194 "fm_sp_assembler.lex"
{
                  return NOT_EQUAL;
               }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 198 "fm_sp_assembler.lex"
{
                  return GREATER_THAN;
               }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 202 "fm_sp_assembler.lex"
{
                  return LESS_THAN;
               }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 206 "fm_sp_assembler.lex"
{
                  return GREATER_THAN_EQUAL;
               }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 210 "fm_sp_assembler.lex"
{
                  return LESS_THAN_EQUAL;
               }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 214 "fm_sp_assembler.lex"
{
                  return PLUS;
               }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 218 "fm_sp_assembler.lex"
{
                  return MINUS;
               }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 222 "fm_sp_assembler.lex"
{
                  return LCV;
               }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 226 "fm_sp_assembler.lex"
{
                  return JMP;
               }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 230 "fm_sp_assembler.lex"
{
                  return NOP;
               }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 234 "fm_sp_assembler.lex"
{
                  return HEADER_BASE;
               }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 238 "fm_sp_assembler.lex"
{
                  return WINDOW_OFFSET;
               }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 242 "fm_sp_assembler.lex"
{
                  return CLEAR;
               }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 246 "fm_sp_assembler.lex"
{
                  return CONFIRM_LAYER_MASK;
               }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 250 "fm_sp_assembler.lex"
{
                  return ETH_HXS;
               }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 254 "fm_sp_assembler.lex"
{
                  return IPV4_HXS;
               }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 258 "fm_sp_assembler.lex"
{
                  return IPV6_HXS;
               }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 262 "fm_sp_assembler.lex"
{
                  return OTH_L3_HXS;
               }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 266 "fm_sp_assembler.lex"
{
                  return TCP_HXS;
               }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 270 "fm_sp_assembler.lex"
{
                  return UDP_HXS;
               }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 274 "fm_sp_assembler.lex"
{
                  return OTH_L4_HXS;
               }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 278 "fm_sp_assembler.lex"
{
                  return RETURN_HXS;
               }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 282 "fm_sp_assembler.lex"
{
                  return NXT_ETH_TYPE;
               }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 286 "fm_sp_assembler.lex"
{
                  return NXT_IP_PROTO;
               }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 290 "fm_sp_assembler.lex"
{
                  return END_PARSE;
               }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 294 "fm_sp_assembler.lex"
{
                  return WR0;
               }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 298 "fm_sp_assembler.lex"
{
                  return WR1;
               }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 302 "fm_sp_assembler.lex"
{
                  return UINT6_TYPE;
               }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 306 "fm_sp_assembler.lex"
{
                  return UINT6_TYPE;
               }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 310 "fm_sp_assembler.lex"
{
                  return UINT7_TYPE;
               }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 314 "fm_sp_assembler.lex"
{
                  return UINT7_TYPE;
               }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 318 "fm_sp_assembler.lex"
{
                  return UINT8_TYPE;
               }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 322 "fm_sp_assembler.lex"
{
                  return UINT16_TYPE;
               }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 326 "fm_sp_assembler.lex"
{
                  return UINT32_TYPE;
               }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 330 "fm_sp_assembler.lex"
{
                  return UINT48_TYPE;
               }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 334 "fm_sp_assembler.lex"
{
                  return UINT64_TYPE;
               }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 338 "fm_sp_assembler.lex"
{
                  return OPEN_PAREN;
               }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 342 "fm_sp_assembler.lex"
{
                  return CLOSE_PAREN;
               }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 346 "fm_sp_assembler.lex"
{
                  return COMMA;
               }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 350 "fm_sp_assembler.lex"
{
                       ((YYSTYPE *)lval_p)->string = strdup(_fmsp_assembler_yytext);

                       if (((YYSTYPE *)lval_p)->string == NULL)
                       {
                          _FMSP_MALLOC_FAIL_EXIT_PARSE
                       }
     
                       return ALPHA_NUMERIC_WORD;
                    }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 361 "fm_sp_assembler.lex"
{
                 /* Eat up other junk */
               }
	YY_BREAK
case YY_STATE_EOF(INITIAL):
#line 365 "fm_sp_assembler.lex"
{
                  yyterminate();
               }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 368 "fm_sp_assembler.lex"
ECHO;
	YY_BREAK
#line 1491 "lex._fmsp_assembler_yy.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed _fmsp_assembler_yyin at a new source and called
			 * _fmsp_assembler_yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = _fmsp_assembler_yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( _fmsp_assembler_yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * _fmsp_assembler_yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of _fmsp_assembler_yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					_fmsp_assembler_yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			_fmsp_assembler_yyrestart(_fmsp_assembler_yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) _fmsp_assembler_yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 246 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 246 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 245);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up _fmsp_assembler_yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					_fmsp_assembler_yyrestart(_fmsp_assembler_yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( _fmsp_assembler_yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve _fmsp_assembler_yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void _fmsp_assembler_yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        _fmsp_assembler_yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            _fmsp_assembler_yy_create_buffer(_fmsp_assembler_yyin,YY_BUF_SIZE );
	}

	_fmsp_assembler_yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	_fmsp_assembler_yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void _fmsp_assembler_yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		_fmsp_assembler_yypop_buffer_state();
	 *		_fmsp_assembler_yypush_buffer_state(new_buffer);
     */
	_fmsp_assembler_yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	_fmsp_assembler_yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (_fmsp_assembler_yywrap()) processing, but the only time this flag
	 * is looked at is after _fmsp_assembler_yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void _fmsp_assembler_yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	_fmsp_assembler_yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE _fmsp_assembler_yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) _fmsp_assembler_yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in _fmsp_assembler_yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) _fmsp_assembler_yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in _fmsp_assembler_yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	_fmsp_assembler_yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with _fmsp_assembler_yy_create_buffer()
 * 
 */
    void _fmsp_assembler_yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		_fmsp_assembler_yyfree((void *) b->yy_ch_buf  );

	_fmsp_assembler_yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a _fmsp_assembler_yyrestart() or at EOF.
 */
    static void _fmsp_assembler_yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	_fmsp_assembler_yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then _fmsp_assembler_yy_init_buffer was _probably_
     * called from _fmsp_assembler_yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void _fmsp_assembler_yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		_fmsp_assembler_yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void _fmsp_assembler_yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	_fmsp_assembler_yyensure_buffer_stack();

	/* This block is copied from _fmsp_assembler_yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from _fmsp_assembler_yy_switch_to_buffer. */
	_fmsp_assembler_yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void _fmsp_assembler_yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	_fmsp_assembler_yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		_fmsp_assembler_yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void _fmsp_assembler_yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)_fmsp_assembler_yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in _fmsp_assembler_yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)_fmsp_assembler_yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in _fmsp_assembler_yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE _fmsp_assembler_yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) _fmsp_assembler_yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in _fmsp_assembler_yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	_fmsp_assembler_yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to _fmsp_assembler_yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       _fmsp_assembler_yy_scan_bytes() instead.
 */
YY_BUFFER_STATE _fmsp_assembler_yy_scan_string (yyconst char * yystr )
{
    
	return _fmsp_assembler_yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to _fmsp_assembler_yylex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE _fmsp_assembler_yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) _fmsp_assembler_yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in _fmsp_assembler_yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = _fmsp_assembler_yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in _fmsp_assembler_yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up _fmsp_assembler_yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		_fmsp_assembler_yytext[_fmsp_assembler_yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = _fmsp_assembler_yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		_fmsp_assembler_yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int _fmsp_assembler_yyget_lineno  (void)
{
        
    return _fmsp_assembler_yylineno;
}

/** Get the input stream.
 * 
 */
FILE *_fmsp_assembler_yyget_in  (void)
{
        return _fmsp_assembler_yyin;
}

/** Get the output stream.
 * 
 */
FILE *_fmsp_assembler_yyget_out  (void)
{
        return _fmsp_assembler_yyout;
}

/** Get the length of the current token.
 * 
 */
int _fmsp_assembler_yyget_leng  (void)
{
        return _fmsp_assembler_yyleng;
}

/** Get the current token.
 * 
 */

char *_fmsp_assembler_yyget_text  (void)
{
        return _fmsp_assembler_yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void _fmsp_assembler_yyset_lineno (int  line_number )
{
    
    _fmsp_assembler_yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see _fmsp_assembler_yy_switch_to_buffer
 */
void _fmsp_assembler_yyset_in (FILE *  in_str )
{
        _fmsp_assembler_yyin = in_str ;
}

void _fmsp_assembler_yyset_out (FILE *  out_str )
{
        _fmsp_assembler_yyout = out_str ;
}

int _fmsp_assembler_yyget_debug  (void)
{
        return _fmsp_assembler_yy_flex_debug;
}

void _fmsp_assembler_yyset_debug (int  bdebug )
{
        _fmsp_assembler_yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from _fmsp_assembler_yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    _fmsp_assembler_yyin = stdin;
    _fmsp_assembler_yyout = stdout;
#else
    _fmsp_assembler_yyin = (FILE *) 0;
    _fmsp_assembler_yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * _fmsp_assembler_yylex_init()
     */
    return 0;
}

/* _fmsp_assembler_yylex_destroy is for both reentrant and non-reentrant scanners. */
int _fmsp_assembler_yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		_fmsp_assembler_yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		_fmsp_assembler_yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	_fmsp_assembler_yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * _fmsp_assembler_yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *_fmsp_assembler_yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *_fmsp_assembler_yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void _fmsp_assembler_yyfree (void * ptr )
{
	free( (char *) ptr );	/* see _fmsp_assembler_yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 368 "fm_sp_assembler.lex"



/* Cleanup */
void _fmsp_assembler_lexical_analyzer_cleanup(void)
{
   _fmsp_assembler_yy_delete_buffer( YY_CURRENT_BUFFER );
}

